### ISSUE TITLE
Calculate CRC32 from digit - how?

### ISSUE THREAD

**Issue by saewave** [SheetJS/js-crc32#11]
Hi!

How I can calculate CRC32 from 32 bit hex digit like 0x200031E0 (CRC should be 0x0AAFD11A) or from 32 bit dec?

**Comment by reviewher** [comment]
`CRC32.buf` can take an array of bytes and `CRC32.bstr` can take a binary string.  Both return a signed 32-bit integer that you can convert to hex through unsigned conversion `>>>0` and `toString(16)`.

To convert the 32-bit number to bytes you can either unwind the bytes manually or use a Uint32Array: 

```js
var num = 0x200031E0;

/* Uint8Array */
var ua = new Uint8Array((new Uint32Array([num])).buffer); // Uint8Array [ 224, 49, 0, 32 ]
(CRC32.buf(ua)>>>0).toString(16); // e9fc314b

/* Array of bytes */
var arr = [], n2 = num; for(var i = 0; i < 4; ++i, n2>>>=8) arr[i] = n2 & 0xFF; // arr = [ 224, 49, 0, 32 ]
(CRC32.buf(arr)>>>0).toString(16); // e9fc314b

/* Binary string */
var bstr = ""; for(i = 0, n2 = num; i < 4; ++i, n2>>>=8) bstr += String.fromCharCode(n2 & 0xFF); // bstr = '\xe0\x31\x00\x20'
(CRC32.bstr(bstr)>>>0).toString(16); // e9fc314b
```

The result is determined to be `0xe9fc314b`.  How did you get that CRC result `0x0AAFD11A`?

**Comment by saewave** [comment]
Thank you, I did something similar you provided, but it would be great to have additional function like CRC32.int or CRC32.hex to calculate CRC without extra code. 

> How did you get that CRC result 0x0AAFD11A?

You are right, the result should be `0xe9fc314b` it was my mistake.

**Comment by michau-krakow** [comment]
> additional function like CRC32.int or CRC32.hex to calculate CRC without extra code

C'mon, splitting number into 4 bytes isn't worth any library support, and calculating 32-but crc from 32-bit number does not seem to be very common use case.
