### ISSUE TITLE
How can I get the hex value of CRC32

### ISSUE THREAD

**Issue by hhovakimyan** [SheetJS/js-crc32#12]
I want to get the hex value of CRC32, but I can not, cause the result is always decimal.  Is the only option to covert decimal to hex format manually.

**Comment by SheetJSDev** [comment]
the return value is a signed 32 bit integer.  `crc>>>0` is an unsigned 32 bit int, `(crc >>>0).toString(16)` is the hex string without padding, and `(crc >>>0).toString(16).padStart(8, '0')` is the hex string with padding
