### ISSUE TITLE
ESM build

### ISSUE THREAD

**Issue by SheetJSDev** [SheetJS/js-crc32#20]

**Comment by atsjo** [comment]
Is this going to happen? This is my only commonjs dependency left in an angular project...

**Comment by SheetJSDev** [comment]
3bd21324dbbd9f286aedf77f1eeb161823963c54 appears to work in local node, deno and vite tests.

- https://github.com/SheetJS/js-crc32/blob/master/crc32.mjs ESM version of standard CRC32
- https://github.com/SheetJS/js-crc32/blob/master/crc32c.mjs ESM version of Castagnoli CRC32C

Will need to do some more tests before publishing

**Comment by atsjo** [comment]
any progress with publishing package...?

**Comment by SheetJSDev** [comment]
NPM inc froze the accounts so we are unable to publish to the https://www.npmjs.com/package/crc-32 endpoint.

To offer continued builds, https://cdn.sheetjs.com/crc-32-latest/crc-32-latest.tgz is a pin to the latest release and https://cdn.sheetjs.com/crc-32-1.2.3/crc-32-1.2.3.tgz is a pin to the (now released) 1.2.3 version.

**Comment by atsjo** [comment]
Will it stay this way, or will you get your accounts reopened?
