### ISSUE TITLE
Can this be used to generate unsigned ints?

### ISSUE THREAD

**Issue by tnrich** [SheetJS/js-crc32#6]
Hey there,

I'm currently using your module like so:

```js
    var bsonObjectid = require('bson-objectid');
    var CRC32 = require('crc-32')

    var MySchemaId = bsonObjectid().str
    var sales_order_id = CRC32.str(MySchemaId)
```

But I'm noticing sometimes the sales_order_id is negative. Is there a way to get the CRC32 module to only output unique positive values?

Thanks so much,
Thomas

**Comment by SheetJSDev** [comment]
For performance reasons we default to using signed integers.  However, if you need an unsigned integer, the best way is to convert using the unsigned right shift operator:

```
CRC32.str(MySchemaId) >>> 0
```
