### ISSUE TITLE
buf() mishandles [3, 0, 0, 0, 0]

### ISSUE THREAD

**Issue by FGasper** [SheetJS/js-crc32#9]
```
> const CRC32_MOD = require('crc-32');
undefined
> CRC32_MOD.buf([3, 0, 0, 0, 0])
-2122150451
>
```

**Comment by FGasper** [comment]
Never mind … I didn’t realize this computes a signed value rather than unsigned.

**Comment by reviewher** [comment]
["The return value is a signed 32-bit integer."](https://github.com/SheetJS/js-crc32#usage)

See the discussion from [an older issue](https://github.com/SheetJS/js-crc32/issues/4#issuecomment-170050796).  Basically V8 has a special optimization for 32-bit signed integers which is generally awesome but performs extremely poorly for naive CRC calculations

**Comment by FGasper** [comment]
Might be nice to include a convenience that does the signed-to-unsigned conversion?

I think it's just: `0xffffffff - ~signed`?

**Comment by reviewher** [comment]
Even easier: `signed >>> 0` :) kinda seems like a waste to add that as a convenience method, but it's probably worth adding that to the README (PRs welcome)
